"""
PresentationAI

Ollama AI Provider
"""

from __future__ import annotations

from typing import Generator

import requests

from requests import Response
from requests.exceptions import (
    ConnectionError,
    Timeout,
    RequestException,
)

from src.ai.providers.base_ai_provider import (
    BaseAIProvider,
)

from src.ai.prompt_builder import (
    PromptBundle,
)


class OllamaProvider(BaseAIProvider):
    """
    Production-ready Ollama Provider.

    Features
    --------
    • Chat API
    • JSON Mode
    • Model Discovery
    • Streaming Ready
    • Configurable Parameters
    • Robust Error Handling
    """

    DEFAULT_HOST = "http://localhost:11434"

    DEFAULT_MODEL = "llama3.1:8b"

    # -------------------------------------------------

    def __init__(
        self,
        host: str = DEFAULT_HOST,
        model: str = DEFAULT_MODEL,
        timeout: int = 300,
    ):

        self.host = host.rstrip("/")

        self.model = model

        self.timeout = timeout

        #
        # Generation Parameters
        #

        self.temperature = 0.3

        self.top_p = 0.9

        self.max_tokens = 4096

        self.context_window = 8192

        self.keep_alive = "30m"

        self._initialized = False

    # -------------------------------------------------

    @property
    def name(self) -> str:

        return "Ollama"

    # -------------------------------------------------

    @property
    def is_local(self) -> bool:

        return True

    # -------------------------------------------------

    @property
    def api_url(self) -> str:

        return f"{self.host}/api/chat"

    # -------------------------------------------------

    @property
    def tags_url(self) -> str:

        return f"{self.host}/api/tags"

    # -------------------------------------------------

    def initialize(self):

        self._initialized = True

    # -------------------------------------------------

    def shutdown(self):

        self._initialized = False

    # -------------------------------------------------

    def ping(self) -> bool:
        """
        Returns True if Ollama server
        is reachable.
        """

        try:

            response = requests.get(

                self.tags_url,

                timeout=3,

            )

            return response.status_code == 200

        except Exception:

            return False

    # -------------------------------------------------

    def available(self) -> bool:

        return self.ping()

    # -------------------------------------------------

    def _request(
        self,
        payload: dict,
        stream: bool = False,
    ) -> Response:
        """
        Internal HTTP request helper.
        """

        try:

            response = requests.post(

                self.api_url,

                json=payload,

                stream=stream,

                timeout=self.timeout,

            )

            response.raise_for_status()

            return response

        except ConnectionError as exc:

            raise RuntimeError(

                "Cannot connect to Ollama."

            ) from exc

        except Timeout as exc:

            raise RuntimeError(

                "Ollama request timed out."

            ) from exc

        except RequestException as exc:

            raise RuntimeError(

                f"Ollama request failed: {exc}"

            ) from exc
        # -------------------------------------------------

    def generate(
        self,
        bundle: PromptBundle,
    ) -> str:
        """
        Generate a complete presentation JSON.

        Returns
        -------
        str
            JSON generated by Ollama.
        """

        if not self.available():

            raise RuntimeError(
                "Ollama server is not running."
            )

        if not self.model_exists():

            raise RuntimeError(
                f'Model "{self.model}" is not installed.'
            )

        payload = {

            "model": self.model,

            "messages": [

                {

                    "role": "system",

                    "content": bundle.system_prompt,

                },

                {

                    "role": "user",

                    "content": (

                        bundle.user_prompt

                        + "\n\n"

                        + bundle.response_schema

                    ),

                },

            ],

            #
            # Production
            #

            "stream": False,

            "format": "json",

            "keep_alive": self.keep_alive,

            "options": {

                "temperature": self.temperature,

                "top_p": self.top_p,

                "num_predict": self.max_tokens,

                "num_ctx": self.context_window,

            },

        }

        response = self._request(
            payload
        )

        data = response.json()

        #
        # Chat API
        #

        message = data.get(
            "message",
            {},
        )

        content = message.get(
            "content",
            "",
        ).strip()

        if not content:

            raise RuntimeError(
                "Ollama returned an empty response."
            )

        return content

    # -------------------------------------------------

    def stream_generate(
        self,
        bundle: PromptBundle,
    ) -> Generator[str, None, None]:
        """
        Streaming generation.

        Yields
        ------
        str
            Partial AI response.
        """

        payload = {

            "model": self.model,

            "messages": [

                {

                    "role": "system",

                    "content": bundle.system_prompt,

                },

                {

                    "role": "user",

                    "content": (

                        bundle.user_prompt

                        + "\n\n"

                        + bundle.response_schema

                    ),

                },

            ],

            "stream": True,

            "format": "json",

            "keep_alive": self.keep_alive,

            "options": {

                "temperature": self.temperature,

                "top_p": self.top_p,

                "num_predict": self.max_tokens,

                "num_ctx": self.context_window,

            },

        }

        response = self._request(

            payload,

            stream=True,

        )

        for line in response.iter_lines():

            if not line:

                continue

            try:

                obj = line.decode("utf-8")

                import json

                chunk = json.loads(obj)

            except Exception:

                continue

            message = chunk.get(
                "message",
                {},
            )

            text = message.get(
                "content",
                "",
            )

            if text:

                yield text
        # -------------------------------------------------

    def list_models(self) -> list[str]:
        """
        Returns installed Ollama models.
        """

        if not self.available():

            return []

        try:

            response = requests.get(

                self.tags_url,

                timeout=10,

            )

            response.raise_for_status()

            data = response.json()

            return [

                model["name"]

                for model in data.get(

                    "models",

                    [],

                )

            ]

        except Exception:

            return []

    # -------------------------------------------------

    def model_exists(
        self,
        model: str | None = None,
    ) -> bool:
        """
        Returns True if model exists.
        """

        model = model or self.model

        return model in self.list_models()

    # -------------------------------------------------

    def set_model(
        self,
        model: str,
    ):

        self.model = model

    # -------------------------------------------------

    def set_host(
        self,
        host: str,
    ):

        self.host = host.rstrip("/")

    # -------------------------------------------------

    def set_timeout(
        self,
        timeout: int,
    ):

        self.timeout = timeout

    # -------------------------------------------------

    def set_generation_options(

        self,

        *,

        temperature: float | None = None,

        top_p: float | None = None,

        max_tokens: int | None = None,

        context_window: int | None = None,

        keep_alive: str | None = None,

    ):
        """
        Update generation parameters.
        """

        if temperature is not None:

            self.temperature = temperature

        if top_p is not None:

            self.top_p = top_p

        if max_tokens is not None:

            self.max_tokens = max_tokens

        if context_window is not None:

            self.context_window = context_window

        if keep_alive is not None:

            self.keep_alive = keep_alive

    # -------------------------------------------------

    def configuration(self) -> dict:
        """
        Returns current configuration.
        """

        return {

            "host": self.host,

            "model": self.model,

            "timeout": self.timeout,

            "temperature": self.temperature,

            "top_p": self.top_p,

            "max_tokens": self.max_tokens,

            "context_window": self.context_window,

            "keep_alive": self.keep_alive,

        }

    # -------------------------------------------------

    @property
    def supports_streaming(self) -> bool:

        return True

    # -------------------------------------------------

    @property
    def supports_json_mode(self) -> bool:

        return True

    # -------------------------------------------------

    @property
    def supports_images(self) -> bool:

        return False

    # -------------------------------------------------

    @property
    def supports_tools(self) -> bool:

        return False

    # -------------------------------------------------

    def __repr__(self):

        return (

            f"<OllamaProvider "

            f"model='{self.model}' "

            f"host='{self.host}'>"

        )